server:
    port: 8085
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/importe
        username: nkharin
        password: postgre
        driver-class-name: org.postgresql.Driver
    flyway:
        schemas: public
        baseline-on-migrate: true
        url: jdbc:postgresql://localhost:5432/importe
        user: "nkharin"
        password: "postgre"